<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Azure.Identity" Version="1.21.0" />
    <PackageVersion Include="Azure.Messaging.ServiceBus" Version="7.20.2" />
    <PackageVersion Include="Azure.Storage.Blobs" Version="12.29.1" />
    <PackageVersion Include="FFMpegCore" Version="5.4.0" />
    <PackageVersion Include="KubernetesClient" Version="19.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
  </ItemGroup>
</Project>