apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patch-analyzer.yaml
  - path: patch-completion.yaml
configMapGenerator:
  - name: video-config
    behavior: merge
    literals:
      - ServiceBus__Namespace=
      - ServiceBus__InputQueue=video-submitted
      - ServiceBus__VideoResultQueue=video-results
