apiVersion: batch/v1
kind: Job
metadata:
  name: video-encoder-template
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
    spec:
      volumes:
        - name: input-storage
          csi:
            driver: blob.csi.azure.com
            volumeAttributes:
              protocol: fuse2
              mountWithWorkloadIdentityToken: "true"
              mountOptions: --allow-other --use-attr-cache=true --file-cache-timeout-in-seconds=300 --cancel-list-on-mount-seconds=10
        - name: output-storage
          csi:
            driver: blob.csi.azure.com
            volumeAttributes:
              protocol: fuse2
              mountWithWorkloadIdentityToken: "true"
              mountOptions: --allow-other --use-attr-cache=true --file-cache-timeout-in-seconds=30 --disable-writeback-cache=true
